// Year In Review — 50 Câu Hỏi Phản Tư Sâu Sắc

export const CATEGORIES = {
  HIGHLIGHTS: { id: 'highlights', label: 'Điểm sáng', icon: '✨', color: '#f59e0b' },
  LESSONS: { id: 'lessons', label: 'Bài học', icon: '🎓', color: '#6366f1' },
  CHALLENGES: { id: 'challenges', label: 'Thử thách', icon: '💪', color: '#ef4444' },
  GROWTH: { id: 'growth', label: 'Phát triển', icon: '🌱', color: '#10b981' },
  RELATIONSHIPS: { id: 'relationships', label: 'Quan hệ', icon: '❤️', color: '#ec4899' },
  REFLECTION: { id: 'reflection', label: 'Nhìn lại', icon: '🪞', color: '#8b5cf6' },
  NEXT_YEAR: { id: 'next_year', label: 'Năm tới', icon: '🚀', color: '#0ea5e9' },
}

// Phần: Năm nay (Q1–Q30)
export const THIS_YEAR_QUESTIONS = [
  {
    id: 'q1',
    number: 1,
    section: 'this_year',
    category: CATEGORIES.LESSONS,
    question: 'Bài học quan trọng nhất bạn học được trong năm nay là gì?',
    placeholder: 'Điều cốt lõi đã thay đổi cách bạn nhìn nhận mọi thứ...',
  },
  {
    id: 'q2',
    number: 2,
    section: 'this_year',
    category: CATEGORIES.HIGHLIGHTS,
    question: 'Điều tốt đẹp nhất đã xảy ra trong năm nay là gì?',
    placeholder: 'Khoảnh khắc hoặc thành tựu bạn trân trọng nhất...',
  },
  {
    id: 'q3',
    number: 3,
    section: 'this_year',
    category: CATEGORIES.CHALLENGES,
    question: 'Bạn đã vượt qua những thử thách nào?',
    placeholder: 'Những rào cản bạn đã đối mặt và vượt qua...',
  },
  {
    id: 'q4',
    number: 4,
    section: 'this_year',
    category: CATEGORIES.LESSONS,
    question: 'Bạn đã học được những kỹ năng mới nào?',
    placeholder: 'Năng lực, kiến thức hoặc kỹ năng mới bạn phát triển...',
  },
  {
    id: 'q5',
    number: 5,
    section: 'this_year',
    category: CATEGORIES.GROWTH,
    question: 'Bạn đã làm gì cho sự nghiệp của mình trong năm nay?',
    placeholder: 'Những bước bạn đã thực hiện để phát triển nghề nghiệp...',
  },
  {
    id: 'q6',
    number: 6,
    section: 'this_year',
    category: CATEGORIES.HIGHLIGHTS,
    question: 'Điều bạn thích nhất trong năm nay là gì?',
    placeholder: 'Những hoạt động, trải nghiệm mang lại niềm vui cho bạn...',
  },
  {
    id: 'q7',
    number: 7,
    section: 'this_year',
    category: CATEGORIES.HIGHLIGHTS,
    question: 'Khoảnh khắc yêu thích nhất của bạn là gì?',
    placeholder: 'Nhắm mắt lại và hình dung khoảnh khắc khiến bạn mỉm cười...',
  },
  {
    id: 'q8',
    number: 8,
    section: 'this_year',
    category: CATEGORIES.HIGHLIGHTS,
    question: 'Bạn đã có những niềm vui gì trong năm nay?',
    placeholder: 'Cách bạn thư giãn, vui chơi và nạp lại năng lượng...',
  },
  {
    id: 'q9',
    number: 9,
    section: 'this_year',
    category: CATEGORIES.GROWTH,
    question: 'Bạn đã bắt đầu những thói quen mới nào?',
    placeholder: 'Những thói quen hoặc nề nếp bạn đã xây dựng trong cuộc sống hàng ngày...',
  },
  {
    id: 'q10',
    number: 10,
    section: 'this_year',
    category: CATEGORIES.GROWTH,
    question: 'Bạn tự hào nhất về điều gì trong năm nay?',
    placeholder: 'Thành tựu bạn tự hào nhất, dù lớn hay nhỏ...',
  },
  {
    id: 'q11',
    number: 11,
    section: 'this_year',
    category: CATEGORIES.LESSONS,
    question: 'Bạn đã học được gì về bản thân mình?',
    placeholder: 'Những hiểu biết mới về chính con người bạn...',
  },
  {
    id: 'q12',
    number: 12,
    section: 'this_year',
    category: CATEGORIES.GROWTH,
    question: 'Bạn đã sống đúng với những giá trị cốt lõi của mình như thế nào?',
    placeholder: 'Những khoảnh khắc hành động của bạn phản ánh điều quan trọng nhất với bạn...',
  },
  {
    id: 'q13',
    number: 13,
    section: 'this_year',
    category: CATEGORIES.RELATIONSHIPS,
    question: 'Các mối quan hệ (gia đình, bạn bè, công việc) của bạn đã thay đổi thế nào?',
    placeholder: 'Sự thay đổi trong cách bạn kết nối với những người xung quanh...',
  },
  {
    id: 'q14',
    number: 14,
    section: 'this_year',
    category: CATEGORIES.REFLECTION,
    question: 'Quyết định tốt nhất bạn đã đưa ra là gì?',
    placeholder: 'Một lựa chọn đã mang lại tác động lớn và đúng đắn...',
  },
  {
    id: 'q15',
    number: 15,
    section: 'this_year',
    category: CATEGORIES.CHALLENGES,
    question: 'Bạn đã thất bại như thế nào?',
    placeholder: 'Trung thực nhìn lại — điều gì không thành công và bạn rút ra được gì...',
  },
  {
    id: 'q16',
    number: 16,
    section: 'this_year',
    category: CATEGORIES.CHALLENGES,
    question: 'Điều gì đã cản trở thành công của bạn?',
    placeholder: 'Những rào cản bên trong hoặc bên ngoài đã kìm hãm bạn...',
  },
  {
    id: 'q17',
    number: 17,
    section: 'this_year',
    category: CATEGORIES.CHALLENGES,
    question: 'Nếu có thể, bạn sẽ làm gì khác đi?',
    placeholder: 'Không hối tiếc — chỉ là nhìn lại trung thực...',
  },
  {
    id: 'q18',
    number: 18,
    section: 'this_year',
    category: CATEGORIES.REFLECTION,
    question: 'Bạn khác gì so với một năm trước?',
    placeholder: 'Tư duy, thói quen, các mối quan hệ hay cách nhìn cuộc sống của bạn...',
  },
  {
    id: 'q19',
    number: 19,
    section: 'this_year',
    category: CATEGORIES.GROWTH,
    question: 'Bạn đã làm gì cho sức khoẻ thể chất và tinh thần?',
    placeholder: 'Cách bạn chăm sóc cơ thể và tâm trí của mình...',
  },
  {
    id: 'q20',
    number: 20,
    section: 'this_year',
    category: CATEGORIES.RELATIONSHIPS,
    question: 'Ai hoặc điều gì đã ảnh hưởng lớn nhất đến cuộc sống của bạn năm nay?',
    placeholder: 'Một người, cuốn sách, trải nghiệm hay ý tưởng đã định hình bạn...',
  },
  {
    id: 'q21',
    number: 21,
    section: 'this_year',
    category: CATEGORIES.REFLECTION,
    question: 'Bạn đã buông bỏ điều gì?',
    placeholder: 'Niềm tin, thói quen, mối quan hệ hay tình huống bạn đã để qua...',
  },
  {
    id: 'q22',
    number: 22,
    section: 'this_year',
    category: CATEGORIES.LESSONS,
    question: 'Những nguồn lực hữu ích nhất bạn có là gì?',
    placeholder: 'Sách, công cụ, con người hay môi trường đã hỗ trợ bạn nhiều nhất...',
  },
  {
    id: 'q23',
    number: 23,
    section: 'this_year',
    category: CATEGORIES.REFLECTION,
    question: 'Bạn biết ơn điều gì trong năm nay?',
    placeholder: 'Những điều lớn và nhỏ đã mang lại lòng biết ơn trong cuộc sống của bạn...',
  },
  {
    id: 'q24',
    number: 24,
    section: 'this_year',
    category: CATEGORIES.REFLECTION,
    question: 'Điều gì bạn còn bỏ dở chưa hoàn thành?',
    placeholder: 'Những dự án, mục tiêu hay cuộc trò chuyện vẫn còn dang dở...',
  },
  {
    id: 'q25',
    number: 25,
    section: 'this_year',
    category: CATEGORIES.RELATIONSHIPS,
    question: 'Lời khen tốt nhất bạn nhận được là gì?',
    placeholder: 'Những lời nói ở lại với bạn và khiến bạn cảm thấy được nhìn nhận...',
  },
  {
    id: 'q26',
    number: 26,
    section: 'this_year',
    category: CATEGORIES.REFLECTION,
    question: 'Nếu năm nay là một câu chuyện, bạn sẽ kể nó như thế nào?',
    placeholder: 'Hãy tưởng tượng một tiêu đề, chủ đề hoặc cung bậc cảm xúc cho năm này...',
  },
  {
    id: 'q27',
    number: 27,
    section: 'this_year',
    category: CATEGORIES.REFLECTION,
    question: 'Bạn mô tả năm nay bằng 3 đến 5 từ khoá như thế nào?',
    placeholder: 'Vd: Bứt phá, Kết nối, Trưởng thành, Khám phá...',
  },
  {
    id: 'q28',
    number: 28,
    section: 'this_year',
    category: CATEGORIES.REFLECTION,
    question: 'Điều gì tiếp thêm năng lượng cho bạn? Điều gì làm bạn kiệt sức?',
    placeholder: 'Nhận ra điều gì mang lại sinh lực và điều gì làm cạn kiệt năng lượng...',
  },
  {
    id: 'q29',
    number: 29,
    section: 'this_year',
    category: CATEGORIES.RELATIONSHIPS,
    question: 'Bạn đã tử tế với bản thân như thế nào?',
    placeholder: 'Lòng tự trắc ẩn, sự nghỉ ngơi và cách bạn đối xử với chính mình...',
  },
  {
    id: 'q30',
    number: 30,
    section: 'this_year',
    category: CATEGORIES.REFLECTION,
    question: 'Bạn sẽ nói gì với bản thân của một năm trước?',
    placeholder: 'Trí tuệ bạn đã tích lũy được, tóm gọn thành một thông điệp gửi cho chính mình...',
  },
]

// Phần: Năm tới (Q31–Q50)
export const NEXT_YEAR_QUESTIONS = [
  {
    id: 'q31',
    number: 31,
    section: 'next_year',
    category: CATEGORIES.NEXT_YEAR,
    question: 'Ý định của bạn cho năm tới là gì?',
    placeholder: 'Chủ đề bao quát hoặc ngôi sao dẫn đường của bạn cho năm tới...',
  },
  {
    id: 'q32',
    number: 32,
    section: 'next_year',
    category: CATEGORIES.NEXT_YEAR,
    question: 'Bạn sẽ tiếp tục làm gì?',
    placeholder: 'Thói quen, thực hành và lựa chọn xứng đáng được duy trì...',
  },
  {
    id: 'q33',
    number: 33,
    section: 'next_year',
    category: CATEGORIES.NEXT_YEAR,
    question: 'Bạn muốn thay đổi hoàn toàn điều gì?',
    placeholder: 'Điều gì cần được làm lại hoặc biến đổi trong cuộc sống của bạn...',
  },
  {
    id: 'q34',
    number: 34,
    section: 'next_year',
    category: CATEGORIES.NEXT_YEAR,
    question: 'Bạn dự định sẽ khác biệt thế nào vào cuối năm tới?',
    placeholder: 'Phiên bản tốt nhất của bạn mà bạn đang hướng tới...',
  },
  {
    id: 'q35',
    number: 35,
    section: 'next_year',
    category: CATEGORIES.NEXT_YEAR,
    question: 'Bạn sẽ làm gì để bước ra khỏi vùng an toàn?',
    placeholder: 'Những thử thách dũng cảm hoặc thử nghiệm bạn cam kết thực hiện...',
  },
  {
    id: 'q36',
    number: 36,
    section: 'next_year',
    category: CATEGORIES.NEXT_YEAR,
    question: 'Bạn sẽ học hỏi như thế nào từ những sai lầm trong tương lai?',
    placeholder: 'Hệ thống hoặc tư duy để biến thất bại thành bước tiến...',
  },
  {
    id: 'q37',
    number: 37,
    section: 'next_year',
    category: CATEGORIES.NEXT_YEAR,
    question: 'Bạn muốn đạt được điều gì?',
    placeholder: 'Những mục tiêu, dự án hoặc cột mốc hàng đầu cho năm tới...',
  },
  {
    id: 'q38',
    number: 38,
    section: 'next_year',
    category: CATEGORIES.NEXT_YEAR,
    question: 'Mục đích của bạn trong năm tới sẽ là gì?',
    placeholder: '"Tại sao" sâu xa hơn đằng sau cách bạn muốn sống và làm việc...',
  },
  {
    id: 'q39',
    number: 39,
    section: 'next_year',
    category: CATEGORIES.NEXT_YEAR,
    question: 'Những mối quan hệ hiện có nào bạn muốn tập trung vào?',
    placeholder: 'Những người bạn muốn đầu tư nhiều thời gian và tâm huyết hơn...',
  },
  {
    id: 'q40',
    number: 40,
    section: 'next_year',
    category: CATEGORIES.NEXT_YEAR,
    question: 'Bạn muốn tạo ra những cơ hội nghề nghiệp nào cho bản thân?',
    placeholder: 'Những bước đi, dự án hoặc sự chuyển hướng nghề nghiệp bạn muốn theo đuổi...',
  },
  {
    id: 'q41',
    number: 41,
    section: 'next_year',
    category: CATEGORIES.NEXT_YEAR,
    question: 'Làm thế nào để năm tới thật sự có ý nghĩa?',
    placeholder: 'Điều gì sẽ khiến năm này cảm thấy sâu sắc và xứng đáng...',
  },
  {
    id: 'q42',
    number: 42,
    section: 'next_year',
    category: CATEGORIES.NEXT_YEAR,
    question: 'Bạn sẽ giúp đỡ người khác như thế nào?',
    placeholder: 'Cách bạn dự định đóng góp, cống hiến hoặc nâng đỡ những người xung quanh...',
  },
  {
    id: 'q43',
    number: 43,
    section: 'next_year',
    category: CATEGORIES.NEXT_YEAR,
    question: 'Bạn muốn củng cố những phẩm chất cá nhân nào?',
    placeholder: 'Những đức tính như kiên nhẫn, kỷ luật hay can đảm bạn muốn rèn giũa...',
  },
  {
    id: 'q44',
    number: 44,
    section: 'next_year',
    category: CATEGORIES.NEXT_YEAR,
    question: 'Bạn muốn học những kỹ năng gì?',
    placeholder: 'Những năng lực mới khiến bạn hứng thú hoặc bạn cần để phát triển...',
  },
  {
    id: 'q45',
    number: 45,
    section: 'next_year',
    category: CATEGORIES.NEXT_YEAR,
    question: 'Bạn sẽ chăm sóc bản thân như thế nào?',
    placeholder: 'Sức khoẻ, sự nghỉ ngơi và các thực hành tự chăm sóc bạn sẽ ưu tiên...',
  },
  {
    id: 'q46',
    number: 46,
    section: 'next_year',
    category: CATEGORIES.NEXT_YEAR,
    question: 'Bạn muốn đến những nơi nào?',
    placeholder: 'Những chuyến phiêu lưu, hành trình hoặc môi trường mới bạn muốn khám phá...',
  },
  {
    id: 'q47',
    number: 47,
    section: 'next_year',
    category: CATEGORIES.NEXT_YEAR,
    question: 'Bạn sẽ nói "không" với điều gì?',
    placeholder: 'Những cam kết, sự xao nhãng hoặc thói quen bạn chọn từ chối...',
  },
  {
    id: 'q48',
    number: 48,
    section: 'next_year',
    category: CATEGORIES.NEXT_YEAR,
    question: 'Bạn sẽ cải thiện môi trường sống của mình như thế nào?',
    placeholder: 'Ngôi nhà, không gian làm việc, vòng kết nối xã hội hoặc cuộc sống số của bạn...',
  },
  {
    id: 'q49',
    number: 49,
    section: 'next_year',
    category: CATEGORIES.NEXT_YEAR,
    question: 'Bạn sẽ nhờ ai giúp đỡ và hỗ trợ?',
    placeholder: 'Người cố vấn, bạn bè hoặc cộng đồng bạn dự định dựa vào...',
  },
  {
    id: 'q50',
    number: 50,
    section: 'next_year',
    category: CATEGORIES.NEXT_YEAR,
    question: 'Bạn muốn trở thành ai vào năm tới?',
    placeholder: 'Vẽ ra bức tranh về phiên bản tốt nhất của bạn vào cuối năm tới...',
  },
]

export const ALL_QUESTIONS = [...THIS_YEAR_QUESTIONS, ...NEXT_YEAR_QUESTIONS]
export const TOTAL_QUESTIONS = ALL_QUESTIONS.length
